name: AutoPR

on:
  push:
    branches:
      - 'develop'

jobs:
  Dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print and Update Secret
        run: |
          if [[ "${{ secrets.LAST_COMMIT_PR }}" == "test_value" ]]; then
            echo "SECRET VALUE IS test_value"
          fi
