name: AutoPR

on:
  push:
    branches:
      - 'develop'

jobs:
  Dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: last-commit
      - name: Create Artifact
        run: |
          ls .
          echo "test commit val" > commit.txt
      - uses: actions/upload-artifact@v3
        with:
          name: last-commit
          path: ./commit.txt
