name: AutoPR

on:
  push:
    branches:
      - 'develop'

jobs:

  Create-PR:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.INTERNAL_TOKEN }}
          repository: mrwyattii/fake-DS-internal
          ref: develop
          path: internal-repo

      - name: cherry pick commit
        continue-on-error: true
        run: |
          echo ${{ github.event_name }}
          cd internal-repo
          git config --global user.name "DEEPSPEED BOT"
          git config --global user.email "test@test.com"
          git fetch https://github.com/mrwyattii/fake-DS.git develop && git cherry-pick FETCH_HEAD --strategy-option octopus

      - name: add modified files
        run: |
          cd internal-repo
          git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: internal-repo
          token: ${{ secrets.INTERNAL_TOKEN }}
