name: AutoPR-Dispatcher

on:
  push:
    branches:
      - 'develop'

jobs:
  Dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "public-merge", "client_payload": { "foo": "bar" }}' https://api.github.com/repos/mrwyattii/fake-DS-internal/dispatches
