name: AutoPR

on:
  push:
    branches:
      - 'develop'

jobs:
  CreateCommitMatrix:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      commits: ${{ steps.get_commits.outputs.commits }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: get_commits
        run: |
            COMMITS_STR=$(git rev-list ${{ secrets.LAST_PR_COMMIT }}..HEAD)
            COMMITS_LIST=$(echo "${COMMITS_STR}" | python3 -c "import sys; print([l.strip() for l in sys.stdin]);")
            echo "commits=${COMMITS_LIST}" >> "${GITHUB_OUTPUT}"
      - name: Update Secret
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh secret set LAST_COMMIT_PR --body $(git rev-parse HEAD)

  CreatePRs:
      runs-on: ubuntu-latest
      needs: CreateCommitMatrix
      strategy:
        matrix:
          commit: ${{fromJSON(needs.CreateCommitMatrix.outputs.commits)}}
      steps:
        - name: List Commits
          run: |
            echo "${{ matrix.commit }}"
