name: AutoPR

on:
  push:
    branches:
      - 'develop'

jobs:
  SetSecret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print and Update Secret
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ "${{ secrets.LAST_COMMIT_PR }}" == "test_value" ]]; then
            echo "SECRET VALUE IS test_value"
          else
            echo "SECRET VALUE DID NOT MATCH"
          fi
          gh secret set LAST_COMMIT_PR --body "test_value"
  CreatePRs:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          commit: git rev-list b7574192d05afdf2bcc3f277494e538b75406704..HEAD
      steps:
        - name: List Commits
          run: |
            echo "${{ matrix.commit }}"
