name: AutoPR

on:
  push:
    branches:
      - 'develop'

jobs:

  Create-PR:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.INTERNAL_TOKEN }}
          repository: ${{ secrets.INTERNAL_REPO }}
          ref: develop
          path: internal-repo

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: Extract data
        run: |
          echo "COMMIT_SHA=${{ github.event.after }}" >> $GITHUB_ENV
          echo "USERNAME=${{ github.event.head_commit.author.username }}" >> $GITHUB_ENV
          echo "PR_NAME=$(echo '${{ github.event.head_commit.message }}' | head -1)" >> $GITHUB_ENV

      - name: cherry pick commit
        continue-on-error: true
        run: |
          cd internal-repo
          git config --global user.name "DEEPSPEED BOT"
          git config --global user.email "test@test.com"
          git fetch https://github.com/mrwyattii/fake-DS.git develop && git cherry-pick FETCH_HEAD --strategy-option octopus

      - name: add modified files
        run: |
          cd internal-repo
          git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: internal-repo
          token: ${{ secrets.INTERNAL_TOKEN }}
          body: |
            AutoPR generated from public repo
            ${{ env.COMMIT_SHA }}
            @${{ env.USERNAME }}
          branch: AutoPR
          branch-suffix: short-commit-hash
          assignees: ${{ env.USERNAME }}
          title: ${{ env.PR_NAME }}
          labels: AutoPR
          author: ${{ env.USERNAME }} <${{ env.USERNAME }}@users.noreply.github.com>
