name: auto-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  sync:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Sync branches
        run: |
          git remote add upstream https://github.com/mrwyattii/fake-DS.git
          git fetch upstream
          git checkout develop
          git rebase upstream/develop
          git push origin develop