name: AutoPR

on:
  push:
    branches:
      - 'develop'

jobs:
  CreateMatrix:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      commits: ${{ steps.get_commits.outputs.commits }}
    steps:
      - uses: actions/checkout@v3
      - name: get_commits
        run: |
            #echo "commits=$(git rev-list b7574192d05afdf2bcc3f277494e538b75406704..HEAD | python3 -c 'import sys; print([l.strip() for l in sys.stdin]);')" >> "$GITHUB_OUTPUT"
            echo "commits=['871c85ff6a9616e532c5e951d63a51ba0641c7d1', '6cd8f5ec623904ce98b76eacba2f6847fced45f2', '3b8191cbd3ebb8fb46cd03d894ec576298cf86ea']" >> "$GITHUB_OUTPUT"
  UpdateSecret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print and Update Secret
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ "${{ secrets.LAST_COMMIT_PR }}" == "test_value" ]]; then
            echo "SECRET VALUE IS test_value"
          else
            echo "SECRET VALUE DID NOT MATCH"
          fi
          gh secret set LAST_COMMIT_PR --body "test_value"
          echo "MATRIX=$(git rev-list b7574192d05afdf2bcc3f277494e538b75406704..HEAD | python3 -c 'import sys; print([l.strip() for l in sys.stdin]);')" >> $GITHUB_ENV
  CreatePRs:
      runs-on: ubuntu-latest
      needs: CreateMatrix
      strategy:
        matrix:
          commit: ${{fromJSON(needs.CreateMatrix.outputs.commits)}}
      steps:
        - name: List Commits
          run: |
            echo "${{ matrix.commit }}"
