name: nv-ds-chat

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      dse_branch:
        description: 'DeepSpeedExamples Branch'
        required: false
        default: 'master'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print vars
        run: |
          echo "DSE Branch: $BRANCH"
          echo "WORKFLOW_DISPATCH: $WORKFLOW_DISPATCH"
          echo "EVENT_CONTEXT: $EVENT_CONTEXT"
        env:
          BRANCH: ${{ inputs.dse_branch }}
          WORKFLOW_DISPATCH: ${{ github.event.workflow_dispatch }}
          EVENT_CONTEXT: ${{ toJSON(github.event) }}

      - name: DS-Chat unit tests
        run: |
          BRANCH="master"
          if [[ ! -z "${{ github.event.inputs.dse_branch }}" ]]; then
              BRANCH="${{ github.event.inputs.dse_branch }}"
          fi
          echo "BRANCH: $BRANCH"
          git clone -b $BRANCH https://github.com/microsoft/DeepSpeedExamples.git
