name: Publish distribution to PyPI

on:
  push:
    tags:
     - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        ref: "develop"
    - name: Get release version from tag
      run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Set release version in file
      run: |
        echo ${{ env.RELEASE_VERSION }} > version.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        DS_BUILD_STRING="" python setup.py sdist
        twine upload dist/*
    - name: Bump patch version
      run: |
        python3 scripts/bump-version.py
    - name: Commit version.txt
      run: |
        git config --global user.name 'mrwyattii'
        git config --global user.email 'mrwyattii@users.noreply.github.com'
        git add version.txt
        git commit -m "Release v${{ env.RELEASE_VERSION }}"
        git push
